### ISSUE TITLE
Lazy offset

### ISSUE THREAD

**Issue by silva96** [hotwired/turbo#322]
Is there any way we can load the lazy frame some pixels before it enters the viewport? This way, users don't see the empty frame for a while when they reach it, and experience feels more smooth. ( I'm using this for an infinite scroll)

Thanks in advance

**Comment by tleish** [comment]
We do something similar, but have a loading spinner in the content before loading.  If your turbo-frame is originally empty (no children or space), you could use CSS.  Something like.

```css
.infinite-scroll turbo-frame[loading="lazy"]:empty {
  margin-top: -100px; /* lazy load offset */
  display: block;
}
```

```html
<div class="infinite-scroll">
  ...
  <turbo-frame id="messages-2" src="/messages?p=2" loading="lazy"></turbo-frame>
</div>
````
